graph TD
rest --> RestClient
DiscordErrorResolver --> RestClient

%% utils
config --> CommandsFsUtils

config --> EmbedTemplatesBuilder

%% manager
ErrorReplyer --> ErrorManager

%% handler
config --> AccessHandler

CommandsFsUtils --> CommandHandler
AccessHandler --> CommandHandler
ErrorManager --> CommandHandler

CommandHandler --> InteractionHandler

config --> EventHandler
client --> EventHandler
container --> EventHandler

%% rest
RestClient --> CommandRegistar
config --> CommandRegistar

%% services
CommandRegistar --> CommandDeclaration
AccessHandler --> CommandDeclaration

client --> DiscordInfos

EmbedTemplatesBuilder --> ErrorReplyer

%% bootstrap
CommandsFsUtils --> SlashCommandInit
CommandDeclaration --> SlashCommandInit


%% Events
client --> ClientReady

InteractionHandler --> InteractionCreate

%% Commands
ErrorManager --> GetInfos
EmbedTemplatesBuilder --> GetInfos
DiscordInfos --> GetInfos

